CREATE DATABASE classconnect;
USE classconnect;

CREATE TABLE users (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
CREATE TABLE usergroups (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE groups (
    subject_id VARCHAR(50) PRIMARY KEY,
	Class_Name VARCHAR(50) UNIQUE NOT NULL,
    class_id VARCHAR(50) UNIQUE NOT NULL,
    group_name VARCHAR(50) UNIQUE NOT NULL
);
